### ISSUE TITLE
ScheduleReport_History.sql is incorrect

### ISSUE THREAD

**Issue by djpirra** [Pulsweb/MyScripts#1]
`CASE
	WHEN HIST.Status = 0 THEN 'Data refresh finished sucessfully'
	WHEN HIST.Status = 0 THEN 'Data refresh is in progress'
	ELSE 'Error during refresh'
END AS RESULT`

should be:
`CASE
	WHEN HIST.Status = 0 THEN 'Data refresh finished sucessfully'
	WHEN HIST.Status = 1 THEN 'Data refresh is in progress'
	ELSE 'Error during refresh`

**Comment by Pulsweb** [comment]
Thank you for the feedback
